### ISSUE TITLE
Provide BACnet objects with local device

### ISSUE THREAD

**Issue by pichler** [openmucextensions/bacnet#1]
Local devices created and used by bacnet4j are also able to provide BACnet objects (so the local device is a BACnet server, see [this wiki page](https://github.com/openmucextensions/bacnet/wiki/Providing-BACnet-objects-%28BACnet-server%29) for details). OpenMUC applications should be able to add and remove objects to/from the local device and change the object's value.

**Comment by danielWQ** [comment]
Basic functionality of serving BACnet object was added in version 0.0.8. Analog and Boolean object types are supported up to now.
