### ISSUE TITLE
Replace settings "localDevicePort" and "remoteDevicePort" by "devicePort"

### ISSUE THREAD

**Issue by danielWQ** [openmucextensions/bacnet#13]
It doesn't make sense to configure different values for remote/local device port. Although, it is confusing to have two different settings for the port.

Replace both setting possibilities by a single one called "devicePort"

**Comment by pichler** [comment]
Solved in commit [ebc0b8d387b35548601e8e13aa43b9cb72823aa3](https://github.com/openmucextensions/bacnet/commit/ebc0b8d387b35548601e8e13aa43b9cb72823aa3)
