### ISSUE TITLE
Programmatically scan for device and objects

### ISSUE THREAD

**Issue by Ben1902** [openmucextensions/bacnet#17]
Hi,

I have dived into the functionallity in OpenMUC and these openmuc extensions. I am trying to create a solution that could do a device and/or bacnet object scan from the terminal (for remote, programmatically scan), just like the jmbus lib can do with the run-script.sh. Is this something that is already done, or should I write my own java program for this?

Best regards
Benjamin Krüger

**Comment by pichler** [comment]
Hi Benjamin,

the BACnet driver provides both functionalities, but usually within the OpenMUC framework, you don't call the methods directly. I did the same job in the [Buildung Flight Recorder](https://github.com/openmucextensions/recorder) project, which can also be found here on Github. For details, see the `updateChannelConfiguration` method in the file [UpdateConfigurationTask.java](https://github.com/openmucextensions/recorder/blob/master/src/main/java/org/openmucextensions/app/recorder/UpdateConfigurationTask.java).

Regards, Mike
